[package]
name = "rusty_data"
version = "0.1.0"
authors = ["aschi2 <austinchi2@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
